name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run package
      # --- Added virtual display step for GUI tests ---
      - name: Start xvfb
        run: |
          export DISPLAY=':99.0'
          nohup Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      # --- Updated test step to use virtual display ---
      - name: Run tests
        env:
          DISPLAY: ':99.0'
        run: npm test
      - name: Package VSIX
        run: npx vsce package --no-dependencies
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ./*.vsix
